### ISSUE TITLE
GH-Workflow: Update Actions

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/dungeon-starter#104]
Die in unseren Workflows verwendeten Actions haben sich teilweise weiter entwickelt. Bitte die aktuellen Versionen im Workflow nutzen.

**Comment by AMatutat** [comment]
@TGrothe Ist das noch relevant oder schon gefixt? Wir hatten so viele Workflow Änderungen, da hab ich den Überblick verloren.

**Comment by TGrothe** [comment]
> @TGrothe Ist das noch relevant oder schon gefixt? Wir hatten so viele Workflow Änderungen, da hab ich den Überblick verloren.

Das ist schon gefixt in #109
