### ISSUE TITLE
GH-Action: SpotBugs für Tests?

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/dungeon-starter#105]
Wollen wir wirklich in den Workflows SpotBugs auch auf die Testfälle anwenden? Hier kommt es ja vor allem auf Lesbarkeit und Korrektheit an, d.h. die üblichen Kriterien wie DRY etc. gelten hier nicht oder nur eingeschränkt. Das würde ich auch auf die typischen Anti-Pattern beziehen, die SpotBugs findet. Checkstyle wenden wir beispielsweise auch nur auf die eigentlichen Sourcen, aber nicht (mehr) auf die Testfälle an.

Andererseits könnte SpotBugs damit potentielle Fehler in den Tests selbst finden?

Das Ticket bezieht sich auf den Job `spotbugs`: `./gradlew spotbugsTest`...

**Comment by TGrothe** [comment]
fixed in #107 

Wir wenden SpotBugs auch auf die Testfälle an. Das ist identisch zu der `core` `.github/workflows/github_ci.yml`.
