### ISSUE TITLE
Den dungeon-starter auflösen, bzw. zu einer Demo machen

### ISSUE THREAD

**Issue by TGrothe** [PM-Dungeon/dungeon-starter#119]
Das bringt mich wieder zum Nachdenken. Wir haben unser Core als Framework - damit könnte man direkt loslegen und den Kram schrittweise aufbauen.

Das Desktop soll für die Studis einen leichteren Einstieg ermöglichen, indem ein paar Sachen schon vorgegeben werden. 

Andererseits haben wir den Quickstart-Guide, den die Studis Schritt für Schritt nachbauen (sollen/können). Damit ist eigentlich der Desktop obsolet, weil man den Quickstart eigentlich auch direkt auf dem Core ausführen könnte, oder? 

Dazu kommt noch die Sache mit den ganzen Konfig-Dateien, die wir in beiden Repos pflegen (müssen).

Wäre es nicht sinnvoller, wenn wir das Desktop-Repo in eine Art Demo umbauen, wo wir bestimmte Basissachen zeigen und die Studis hier bestimmte Techniken studieren lassen? Also nicht so sehr als Startpunkt für die eigene Entwicklung, sondern eher eine Art Studienobjekt? Dann könnte man auch (wie die Studis dann) auf Core aufsetzen (als Klon) und würde sich zusätzlich ersparen, welches der beiden Repos denn nun die Source-of-Truth ist (Wie oft haben wir den Quickstart hin und her geschoben? Wie oft kopieren wir Dinge von dem einen Repo ins andere?).

@TGrothe @AMatutat @jedi101 Meinungen? Lohnt sich ein neues Ticket, um darüber nachzudenken?

_Originally posted by @cagix in https://github.com/PM-Dungeon/dungeon-starter/pull/114#discussion_r888805420_

**Comment by TGrothe** [comment]
> > @TGrothe @AMatutat @jedi101 Meinungen? Lohnt sich ein neues Ticket, um darüber nachzudenken?

> Ja, ich finde die Überlegung aus den genannten Gründen sinnvoll ...

> Ein "Nachteil wäre natürlich aus meiner Sicht, dass dann direkte Änderungen am Core möglich wären...

**Comment by jedi101** [comment]
> Ein "Nachteil wäre natürlich aus meiner Sicht, dass dann direkte Änderungen am Core möglich wären...

Hm, das stimmt. Wäre das denn eigentlich schlimm? Die Studis die fit genug sind um den Core umzuschreiben um ihre Art des Dungeon zu implementieren können das meiner Meinung auch gerne machen und für alle anderen bietet der Quickstartguide dann eine entsprechende Vorlage um sich mit dem Framework vertraut zu machen. Aber ich glaube @AMatutat hatte da, als das Thema das letzte mal aufkam, ein Paar Punkte aufgeführt die es dabei zu bedenken gab?

**Comment by AMatutat** [comment]
> Ein "Nachteil wäre natürlich aus meiner Sicht, dass dann direkte Änderungen am Core möglich wären...

Für mich ist das der Entscheidende Punkt, der für einen Merge der Beiden Sachen spricht. Die Aufteilung steht aktiv im weg, wenn man am `core` selbst basteln/experimentieren will. 
Das Problem ist aber, dass wir dann keine einfachen Updates mehr shippen können. Die Studis die am `core` rumbasteln rennen sonst in Mergekonflikte. Auf der anderen Seite, wer fit genug ist am `core` zu schrauben bekommt ein paar Konflikte auch hin. Außerdem wollen wir ja eigentlich eh irgendwann mal eine stable Version haben, an der nix gebaut werden muss.

**Comment by cagix** [comment]
> > Ein "Nachteil wäre natürlich aus meiner Sicht, dass dann direkte Änderungen am Core möglich wären...
> 
> Für mich ist das der entscheidende Punkt, der für einen Merge der Beiden Sachen spricht. Die Aufteilung steht aktiv im Weg, wenn man am `core` selbst basteln/experimentieren will. 

ack.


> Das Problem ist aber, dass wir dann keine einfachen Updates mehr shippen können. Die Studis die am `core` rumbasteln rennen sonst in Mergekonflikte. Auf der anderen Seite, wer fit genug ist am `core` zu schrauben bekommt ein paar Konflikte auch hin. 

Genau. Merge-Konflikte sollte es nur geben, wenn jemand im Vorgabecode (Core) rumspielt. Aber wer das macht, macht das eben auf eigene Gefahr: "Here be dragons ...".

> Außerdem wollen wir ja eigentlich eh irgendwann mal eine stable Version haben, an der nix gebaut werden muss.

Was zur Vermeidung von Merge-Konflikten beitragen sollte. Selbst die Leute, die in Core rumspielen, können dies ja in einer stable-Release machen und kommen damit durchs Semester.

Klingt erstmal nach nem Plan. Aber es gibt bestimmt irgendwo nen Catch.

**Comment by TGrothe** [comment]
Hm, der Pitfall wäre glaube ich wirklich, dass wir dann keine Versionsreleases mehr bereitstellen könnten, mit denen "interne Änderungen" einfach in den Studi-Code integriert werden könnten.

Andererseits könnten sie Studis die Änderungen direkt "sehen", aber der Git-Aufwand wäre bei Änderungen etwas größer.

Und wie gesagt, eigene Änderungen wären fast uneingeschränkt möglich, solange es keine pull oder merge Konflikte gäbe.

**Comment by AMatutat** [comment]
Entscheidung vom 03.06

- die beiden Repos werden gemerged
- dungeon-starter wird ein package im core
- wir stellen im core ein build script zur verfügung zum bauen. 
- dokumentation/wiki geht dann auch alles rüber nach core

**Comment by AMatutat** [comment]
@AMatutat Ich zieh hier Dienstag den Stecker.
