### ISSUE TITLE
[FEATURE] How to import 

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/dungeon-starter#66]
Der Quickstart (oder doch lieber das wiki?) soll um eine "So importieren Sie das Projekt in Ihrer IDE" erweitert werden, Erstmal für Ij und eclipse und vscode. 

https://github.com/PM-Dungeon/desktop/wiki/Import-Project
- [x] Eclipse
- [x] IJ
- [x] VS-Code

edit: added "vscode" 🤷

**Comment by AMatutat** [comment]
Ich versteh das nicht.
Ich hab das Ding in Eclipse mit "import-> gradle project" eingerichtet und los gings....

**Comment by cagix** [comment]
lasst uns den spass nicht übertreiben. also importieren/starten des projekts, vielleicht noch ein paar stolpersteine. aber das muss reichen.

**Comment by jedi101** [comment]
Ich glaube ein Problem worauf die Studis beim ersten Einrichten des Projekts stoßen werden ist, dass sie beim import nicht den `...\desktop\code` Ordner in ihren IDEs als "Projekt root directory" definieren; so wie das Tobias hier im Wiki schon erwähnt hat. -> [Wiki Eclipsesetup](https://github.com/PM-Dungeon/desktop/wiki/FAQ#problem-eclipse-stellt-sich-beim-import-des-projekts-quer) - Und ich kann nur jedem empfehlen das Terminal zum clonen des Repos zu verwenden. Dieser ganze "IDE clutter overhead" mit den zig Importassistenten ist alles Käse meiner Meinung nach.

**Comment by cagix** [comment]
@jedi101 @Tobias321 mal ne dumme frage: was genau ist der `...\desktop\code`-ordner? also insbesondere, was bedeuten die "..." in diesem kontext? 

und warum ist das in windows-notation? in java denken wir unixoid :)

**Comment by Tobias321** [comment]
> Ich glaube ein Problem worauf die Studis beim ersten Einrichten des Projekts stoßen werden ist, dass sie beim import nicht den `...\desktop\code` Ordner in ihren IDEs als "Projekt root directory" definieren; so wie das Tobias hier im Wiki schon erwähnt hat. -> [Wiki Eclipsesetup](https://github.com/PM-Dungeon/desktop/wiki/FAQ#problem-eclipse-stellt-sich-beim-import-des-projekts-quer) - Und ich kann nur jedem empfehlen das Terminal zum clonen des Repos zu verwenden. Dieser ganze "IDE clutter overhead" mit den zig Importassistenten ist alles Käse meiner Meinung nach.

Ich hab mal einen (rudimentären?) Wiki-Eintrag in den FAQ hinzugefügt. Bei mir hat es damit funktioniert, ich habe vorhin diese Eclipse-Version gezogen:

![image](https://user-images.githubusercontent.com/85501570/162259928-b859b7cd-67f5-48d9-a193-f2ec59ec86c6.png)

Windows x86_64

> @jedi101 @Tobias321 mal ne dumme frage: was genau ist der `...\desktop\code`-ordner? also insbesondere, was bedeuten die "..." in diesem kontext?
> 
> und warum ist das in windows-notation? in java denken wir unixoid :)

Jap, dort sollten eigentlich keine Backslashes, sondern Forwardslashes sein... "..." soll der absolute Pfad zum Repository-Ordner sein.

**Comment by jedi101** [comment]
Die `...` stehen für den Ordner in den man das repo gecloned hat. z.B. in den Ordner `/c/Users/Wuppi/Coding/pmdungeon/desktop/code`  mit `cd /c/Users/Wuppi/Coding/ && git clone https://github.com/PM-Dungeon/desktop.git && code .`

**Comment by Tobias321** [comment]
> Wählen Sie als "Projekt root directory" `<absolute path to repo>/desktop/code` aus

**Comment by cagix** [comment]
> Die `...` stehen für den Ordner in den man das repo gecloned hat. z.B. in den Ordner `/c/Users/Wuppi/Coding/pmdungeon/desktop/code` mit `cd /c/Users/Wuppi/Coding/ && mkdir pmdungeon && cd pmdungeon && git clone https://github.com/PM-Dungeon/desktop.git && code desktop/code/` (Das ist im übrigen auch schon der ganze "Setupguide" für Visual Studio Code 👀)

alter! wie soll man denn darauf kommen? ... na gut, man könnte darauf kommen ;)  aber besser ist der vorschlag von @Tobias321 in https://github.com/PM-Dungeon/desktop/issues/66#issuecomment-1092011688.

**Comment by cagix** [comment]
Hier ist nix mehr zu tun, oder?
