### ISSUE TITLE
[BUG] Schließen des Dungeon-Fenster klappt nicht

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/dungeon-starter#74]
Das Schließen des Dungeon-Fensters bewirkt ... NICHTS. Man muss Gradle "abschiessen".

**Comment by AMatutat** [comment]
MacOS?

**Comment by cagix** [comment]
> @cagix MacOS? 

ja, leider.

**Comment by AMatutat** [comment]
Unter Windows10 habe ich das Problem nicht, daher **könnte** es sich um ein OS-Problem handeln

**Comment by cagix** [comment]
> Unter Windows10 habe ich das Problem nicht, daher **könnte** es sich um ein OS-Problem handeln 

möglich. haben wir os-flairs? dann könnten wir hier ein label "mac" dran hängen und mal abwarten ...

**Comment by Tobias321** [comment]
in Win10 kann ich es auch nicht nachstellen

**Comment by cagix** [comment]
lasst uns ein mac-label dran pappen und auf later setzen.

**Comment by cagix** [comment]
Vermutlich lag es an den Exceptions. So lange wie der Starter normal läuft, kann ich das Fenster auch normal schließen.
