### ISSUE TITLE
[BUG] Anleitung zum ersten Hero: Teil zum "getPainter" fehlt

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/dungeon-starter#80]
In der Anleitung zum ersten eigenen Helden (siehe https://github.com/PM-Dungeon/desktop/blob/master/documentation/quickstart_de.md#eigener-held, bis nächsten Abschnitt "Intermezzo: Der Assets-Ordner") fehlt ein Hinweis, dass man in `MyHero#getPainter` ein `return painter;` einbauen sollte.

**Comment by AMatutat** [comment]
Vorschlag zur Vereinfachung:
Wir geben eine abstrakte Klasse Entity vor, die das vor implementiert. Dann fällt das für die Studis weg.

**Comment by cagix** [comment]
> Vorschlag zur Vereinfachung:
> 
> Wir geben eine abstrakte Klasse Entity vor, die das vor implementiert. Dann fällt das für die Studis weg. 
> 
> 

ohne meinem @Tobias321 sage ich nichts 🤣

klingt nach einer idee, wobei ich die tieferen auswirkungen grad nicht überblicke..

**Comment by AMatutat** [comment]
> klingt nach einer idee, wobei ich die tieferen auswirkungen grad nicht überblicke..

ich auch nicht....

**Comment by Tobias321** [comment]
ich muss mir https://github.com/PM-Dungeon/core/pull/227 morgen nochmal in ruhe anschauen...
