### ISSUE TITLE
[Question] Sound deaktivieren

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/dungeon-starter#87]
Hm, wenn man LWJGL (anstatt LWJGL3) verwendet, dann gibt es bei Macs wohl eine warning. Das Deaktivieren der Sounds ist aber eigentlich nicht nötig.

Wir können mit der warning leben oder LWJGL3 verwenden, dann muss der DesktopLauncher aber geändert werden.

_Originally posted by @Tobias321 in https://github.com/PM-Dungeon/desktop/pull/83#discussion_r846976245_

**Comment by cagix** [comment]
@Tobias321 Sehe ich das richtig, dass #87 dieses Issue auch mit fixen wird?

**Comment by Tobias321** [comment]
> @Tobias321 Sehe ich das richtig, dass #86 dieses Issue auch mit fixen wird?

Jap 🙂
