### ISSUE TITLE
Rename "desktop"-Repo to "dungeon-starter"

### ISSUE THREAD

**Issue by TGrothe** [PM-Dungeon/dungeon-starter#88]
Können wir `desktop` umbenennen in `desktop-starter` oder `dungeon-starter`, oder hätte dies dann ungeahnte Nebeneffekte?

**Comment by AMatutat** [comment]
Wir müssten unsere Dokumente überarbeiten aber ansonsten sehe ich keine Probleme

**Comment by cagix** [comment]
Es sollten eigentlich keine Auswirkungen haben, außer:

- Lokale Workingcopy: Remote anpassen (eine Weile läuft es auch noch mit dem alten Namen, aber wer weiss wie lange)
- Im Repo: Suche über alle Dateien nach "desktop" und "PM-Dungeon/desktop" und ggf. ersetzen
- Im Semester-Repo muss vermutlich der alte Subtree gelöscht und ein neuer angelegt werden (habe ich noch nie gemacht, aber bei Submodules wäre es so ungefähr)
- Wiki: Suche über alle Dateien nach "desktop" und "PM-Dungeon/desktop" und ggf. ersetzen
- Lecture-Repo: Suche über alle Dateien nach "desktop" und "PM-Dungeon/desktop" und ggf. ersetzen
- Vorgabe-Repo: Suche über alle Dateien nach "desktop" und "PM-Dungeon/desktop" und ggf. ersetzen

**Comment by AMatutat** [comment]
rename wurde durchgeführt.
Ich pass das im Quickstart direkt mit an,
@Tobias321 bitte einmal auf Spurensuche gehen, wo das ausgetauscht werden muss.

**Comment by Tobias321** [comment]
> @Tobias321 bitte einmal auf Spurensuche gehen, wo das ausgetauscht werden muss.

gsd, in Issues, PRs und Kommentaren werden alle Links automatisch geändert, insofern sie richtig verlinkt wurden...

Ich schau mal im Wiki.

**Comment by Tobias321** [comment]
- [ ] Links in Issues sind ok
- [ ] https://github.com/PM-Dungeon/dungeon-starter/wiki ist überarbeitet
- [ ] https://github.com/PM-Dungeon/core/wiki ist überarbeitet

**Comment by cagix** [comment]
Ich habe mal alle meine Workingcopies aktualisiert und im `master` nach "desktop" gesucht. Hier die relevanten Ergebnisse:

## core

```
pm-dungeon-core % grep -r "desktop" *
README.md:This is the `core` part of the project. It contains the actual framework without any launcher implementation. You can use it to develop your own game, but it is probably easier to use the [desktop](https://github.com/PM-Dungeon/desktop) project as a starting point for your own game. 
README.md:- [German](https://github.com/PM-Dungeon/desktop/blob/master/documentation/quickstart_de.md)
README.md:- [English](https://github.com/PM-Dungeon/desktop/blob/master/documentation/quickstart_en.md)
```

## dungeon-starter

```
pm-dungeon-desktop % grep -r "desktop" *
README.md:Dieses Projekt wird für den einfacheren Zugriff als Git-Subtree im Unterordner "`desktop/`" im Semester-Repository bereitgestellt.
code/build.gradle:eclipse.project.name = "pmdungeon-desktop"
documentation/quickstart_en.md:The framework is divided into `core` and `desktop`, where `core` is the framework and `desktop` is a basic starter.
documentation/quickstart_en.md:To use the PM-Dungeon framework, create a fork of the [`desktop` repository](https://github.com/PM-Dungeon/desktop) and pull a local clone onto your device.
documentation/quickstart_en.md:The PM-Dungeon currently uses the cross-platform Java framework [`libGDX`](https://libgdx.com) as a backend. This is already integrated in the `core` and `desktop` project as a dependency in the Gradle configuration, you do not need to install it separately. The provided PM-Dungeon-Framework is implemented in such a way that you do not need a deeper understanding of the framework or `libGDX` to solve the tasks. However, should you encounter problems, it may help to have a look at the documentation of `libGDX`.
documentation/quickstart_en.md:The framework is divided into a frontend ([`desktop`]((https://github.com/PM-Dungeon/desktop))) and a backend ([`core`]((https://github.com/PM-Dungeon/core)).
documentation/quickstart_en.md:The files given in the [`desktop` repository](https://github.com/PM-Dungeon/desktop) are already executable and can be run directly.
documentation/quickstart_en.md:To do this, go to the `desktop/code` directory, open the command line and enter the following command:
documentation/quickstart_en.md:_Note_: If you have problems starting the application, please check the [FAQ](https://github.com/PM-Dungeon/desktop/wiki/FAQ#problem--gradle-konfiguration-wird-nicht-erkannt). If you still cannot solve your problem, please contact us **early**.
documentation/quickstart_en.md:To do this, open the `desktop/code` directory as a Gradle project in your favourite IDE.
documentation/quickstart_en.md:Let us now look at `desktop.MyGame.java`. This class is your entry point into the dungeon. This is where you will later create your content and add it to the dungeon.
documentation/quickstart_en.md:In the folder [`code/assets/`](https://github.com/PM-Dungeon/desktop/tree/master/code/assets) all assets that will be used in the dungeon are stored. Assets are basically the textures that will be drawn later.
documentation/quickstart_en.md:The assets folder can also be **renamed** or **moved** to another location: To do this, adjust the path `sourceSets.main.resources.srcDirs = ["assets/"]` in the [`build.gradle`](https://github.com/PM-Dungeon/desktop/blob/master/code/build.gradle) file.
documentation/quickstart_en.md:**Example:** You want to move the folder `desktop/code/assets/` to `desktop/code/bar/wuppie/`, then change `sourceSets.main.resources.srcDirs = ["assets/"]` to `sourceSets.main.resources.srcDirs = ["bar/wuppie/"]`.
documentation/quickstart_en.md:Note that the folder can only be renamed/moved within `desktop/code/`.
```


## Dungeon-Solutions

```
pm-dungeon-solutions % grep -r "desktop" *       
code/build.gradle:eclipse.project.name = "pmdungeon-desktop"
```


## PM-Lecture

```
pm-lecture % grep -r "desktop" *
markdown/assignments/pool_dungeon/group_a/dungeon-start.md:Implementieren Sie mithilfe des [Quick-Starts](https://github.com/PM-Dungeon/desktop/blob/master/documentation/quickstart_de.md) Ihren ersten Dungeon und Ihren Helden.
```


## PM-Lecture WIKI

```
pm-lecture-wiki % grep -r "desktop" *  
Konzept.md:Für das Dungeon forken die Studis sich das desktop-repo. Die Dungeonaufgben werden wie üblich im Praktikum vorgestellt.
```


## pm-s22-vorgaben

```
pm-s22-vorgaben % grep -r "desktop" *
LICENSE.md:The contents of the subfolders [`desktop/`](./desktop/) and [`assignment-stubs/`](./assignment-stubs/) are included as a Git subtree from the repositories [PM-Dungeon/desktop](https://github.com/PM-Dungeon/desktop) and [PM-Dungeon/Assignment-Stubs](https://github.com/PM-Dungeon/Assignment-Stubs) and are licensed under a different license (see `LICENSE.md` in the respective folders). The rest of the content of this repository is licensed under CC BY-SA 4.0.
README.md:The contents of the subfolders [`desktop/`](./desktop/) and [`assignment-stubs/`](./assignment-stubs/) are included as a Git subtree from the repositories [PM-Dungeon/desktop](https://github.com/PM-Dungeon/desktop) and [PM-Dungeon/Assignment-Stubs](https://github.com/PM-Dungeon/Assignment-Stubs) and are licensed under a different license (see `LICENSE.md` in the respective folders).
dungeon/documentation/quickstart_en.md:The framework is divided into `core` and `desktop`, where `core` is the framework and `desktop` is a basic starter.
dungeon/documentation/quickstart_en.md:To use the PM-Dungeon framework, create a fork of the [`desktop` repository](https://github.com/PM-Dungeon/desktop) and pull a local clone onto your device.
dungeon/documentation/quickstart_en.md:The PM-Dungeon currently uses the cross-platform Java framework [`libGDX`](https://libgdx.com) as a backend. This is already integrated in the `core` and `desktop` project as a dependency in the Gradle configuration, you do not need to install it separately. The provided PM-Dungeon-Framework is implemented in such a way that you do not need a deeper understanding of the framework or `libGDX` to solve the tasks. However, should you encounter problems, it may help to have a look at the documentation of `libGDX`.
dungeon/documentation/quickstart_en.md:The framework is divided into a frontend ([`desktop`]((https://github.com/PM-Dungeon/desktop))) and a backend ([`core`]((https://github.com/PM-Dungeon/core)).
dungeon/documentation/quickstart_en.md:The files given in the [`desktop` repository](https://github.com/PM-Dungeon/desktop) are already executable and can be run directly.
dungeon/documentation/quickstart_en.md:To do this, go to the `desktop/code` directory, open the command line and enter the following command:
dungeon/documentation/quickstart_en.md:_Note_: If you have problems starting the application, please check the [FAQ](https://github.com/PM-Dungeon/desktop/wiki/FAQ#problem--gradle-konfiguration-wird-nicht-erkannt). If you still cannot solve your problem, please contact us **early**.
dungeon/documentation/quickstart_en.md:To do this, open the `desktop/code` directory as a Gradle project in your favourite IDE.
dungeon/documentation/quickstart_en.md:Let us now look at `desktop.MyGame.java`. This class is your entry point into the dungeon. This is where you will later create your content and add it to the dungeon.
dungeon/documentation/quickstart_en.md:In the folder [`code/assets/`](https://github.com/PM-Dungeon/desktop/tree/master/code/assets) all assets that will be used in the dungeon are stored. Assets are basically the textures that will be drawn later.
dungeon/documentation/quickstart_en.md:The assets folder can also be **renamed** or **moved** to another location: To do this, adjust the path `sourceSets.main.resources.srcDirs = ["assets/"]` in the [`build.gradle`](https://github.com/PM-Dungeon/desktop/blob/master/code/build.gradle) file.
dungeon/documentation/quickstart_en.md:**Example:** You want to move the folder `desktop/code/assets/` to `desktop/code/bar/wuppie/`, then change `sourceSets.main.resources.srcDirs = ["assets/"]` to `sourceSets.main.resources.srcDirs = ["bar/wuppie/"]`.
dungeon/documentation/quickstart_en.md:Note that the folder can only be renamed/moved within `desktop/code/`.
dungeon/code/build.gradle:eclipse.project.name = "pmdungeon-desktop"
dungeon/README.md:Dieses Projekt wird für den einfacheren Zugriff als Git-Subtree im Unterordner "`desktop/`" im Semester-Repository bereitgestellt.
```

**Comment by cagix** [comment]
@Tobias321 

Mir scheint, dass es vor allem in den einzelnen `README.md` und `LICENSE.md` noch umbenannt werden muss. 

Außerdem gibt es im `core` einen Eclipse-bezogenen Eintrag. (Brauchen wir den überhaupt?!)

Der engl. Quickstart muss eh an die neue deutsche Variante angepasst werden, d.h. das kann für die Zwischenzeit ignoriert werden.

---

Bitte in `pm-s22-vorgaben` nicht die Subtrees editieren, also nicht in den Unterordnern direkt arbeiten. Die werden automatisch aktualisiert beim nächsten Updaten ... Hier also nur das `README.md` und die `LICENSE.md`, die Top-Level liegen.

---

Sollte man nochmal drüber nachdenken, das Package `desktop` irgendwie umzubenennen? Der Name ist ja historisch gewachsen und kommt aus der libGDX Start-Konfiguration. Andererseits ist das ja der Desktop-Teil (im Vergleich zu Web oder Android oder so)?

@AMatutat @Tobias321  Meinungen?

**Comment by Tobias321** [comment]
> Außerdem gibt es im `core` und `dungeon-starter` und `Dungeon-Solutions` im Gradle einen Eclipse-bezogenen Eintrag. (Brauchen wir den überhaupt?!)

Gute Frage. Es funktioniert auch ohne diesen Eclipse-bezogenen Eintrag/Varaible. Das ist vermutlich noch etwas vom HTML. Ich war mir aber "damals" nicht sicher, ob dieser Eintrag/Variable noch gebraucht wird, und hatte ihn deshalb drin gelassen.

**Comment by cagix** [comment]
> > Außerdem gibt es im `core` und `dungeon-starter` und `Dungeon-Solutions` im Gradle einen Eclipse-bezogenen Eintrag. (Brauchen wir den überhaupt?!)
> 
> Gute Frage. Es funktioniert auch ohne diesen Eclipse-bezogenen Eintrag/Variable. Das ist vermutlich noch etwas vom HTML. Ich war mir aber "damals" nicht sicher, ob dieser Eintrag/Variable noch gebraucht wird, und hatte ihn deshalb drin gelassen.

Ich würde mal sagen: Wir unterstützen keine IDE. Also raus damit. Wer Eclipse nutzt, kann sich ja das ggf. wieder reinklöppeln. Außerdem gab es ja auch mal ein Plugin `eclipse`, was dann einen Task mitgebracht hat zur Erstellung einer Konfiguration für Eclipse (weiss aber nicht, ob das noch existiert und/oder nötig ist).

**Comment by Tobias321** [comment]
> > > Außerdem gibt es im `core` und `dungeon-starter` und `Dungeon-Solutions` im Gradle einen Eclipse-bezogenen Eintrag. (Brauchen wir den überhaupt?!)
> > 
> > 
> > Gute Frage. Es funktioniert auch ohne diesen Eclipse-bezogenen Eintrag/Variable. Das ist vermutlich noch etwas vom HTML. Ich war mir aber "damals" nicht sicher, ob dieser Eintrag/Variable noch gebraucht wird, und hatte ihn deshalb drin gelassen.
> 
> Ich würde mal sagen: Wir unterstützen keine IDE. Also raus damit. Wer Eclipse nutzt, kann sich ja das ggf. wieder reinklöppeln. Außerdem gab es ja auch mal ein Plugin `eclipse`, was dann einen Task mitgebracht hat zur Erstellung einer Konfiguration für Eclipse (weiss aber nicht, ob das noch existiert und/oder nötig ist).

Gerade getestet, `appName = "pmdungeon"` und `eclipse.project.name = appName + "-..."` kann raus

**Comment by cagix** [comment]
> > > > Außerdem gibt es im `core` und `dungeon-starter` und `Dungeon-Solutions` im Gradle einen Eclipse-bezogenen Eintrag. (Brauchen wir den überhaupt?!)
> > > 
> > > 
> > > Gute Frage. Es funktioniert auch ohne diesen Eclipse-bezogenen Eintrag/Variable. Das ist vermutlich noch etwas vom HTML. Ich war mir aber "damals" nicht sicher, ob dieser Eintrag/Variable noch gebraucht wird, und hatte ihn deshalb drin gelassen.
> > 
> > 
> > Ich würde mal sagen: Wir unterstützen keine IDE. Also raus damit. Wer Eclipse nutzt, kann sich ja das ggf. wieder reinklöppeln. Außerdem gab es ja auch mal ein Plugin `eclipse`, was dann einen Task mitgebracht hat zur Erstellung einer Konfiguration für Eclipse (weiss aber nicht, ob das noch existiert und/oder nötig ist).
> 
> Gerade getestet, `appName = "pmdungeon"` und `eclipse.project.name = appName + "-..."` kann raus

nur zur sicherheit: auf der konsole mit `gradle clean` und `gradle run` getestet? (in der ide reicht mir grad nicht)

**Comment by Tobias321** [comment]
> > > > > Außerdem gibt es im `core` und `dungeon-starter` und `Dungeon-Solutions` im Gradle einen Eclipse-bezogenen Eintrag. (Brauchen wir den überhaupt?!)
> > > > 
> > > > 
> > > > Gute Frage. Es funktioniert auch ohne diesen Eclipse-bezogenen Eintrag/Variable. Das ist vermutlich noch etwas vom HTML. Ich war mir aber "damals" nicht sicher, ob dieser Eintrag/Variable noch gebraucht wird, und hatte ihn deshalb drin gelassen.
> > > 
> > > 
> > > Ich würde mal sagen: Wir unterstützen keine IDE. Also raus damit. Wer Eclipse nutzt, kann sich ja das ggf. wieder reinklöppeln. Außerdem gab es ja auch mal ein Plugin `eclipse`, was dann einen Task mitgebracht hat zur Erstellung einer Konfiguration für Eclipse (weiss aber nicht, ob das noch existiert und/oder nötig ist).
> > 
> > 
> > Gerade getestet, `appName = "pmdungeon"` und `eclipse.project.name = appName + "-..."` kann raus
> 
> nur zur sicherheit: auf der konsole mit `gradle clean` und `gradle run` getestet? (in der ide reicht mir grad nicht)

ja, gerade eben, funktioniert

**Comment by AMatutat** [comment]
> Sollte man nochmal drüber nachdenken, das Package desktop irgendwie umzubenennen? Der Name ist ja historisch gewachsen und kommt aus der libGDX Start-Konfiguration. Andererseits ist das ja der Desktop-Teil (im Vergleich zu Web oder Android oder so)?

Package sollte, aufgrund der genannten Faktoren, weiter `desktop` heißen.

**Comment by Tobias321** [comment]
> > Sollte man nochmal drüber nachdenken, das Package desktop irgendwie umzubenennen? Der Name ist ja historisch gewachsen und kommt aus der libGDX Start-Konfiguration. Andererseits ist das ja der Desktop-Teil (im Vergleich zu Web oder Android oder so)?
> 
> Package sollte, aufgrund der genannten Faktoren, weiter `desktop` heißen.

ja, das denke ich auch...

**Comment by cagix** [comment]
passt für mich. wollte die frage nur mal in die luft werfen  :)

**Comment by Tobias321** [comment]
> passt für mich. wollte die frage nur mal in die luft werfen :)

danke dafür :) wie gesagt, das ist mir schon mal "so halb aufgefallen", war aber in meinem Kopf iwie auf "later" gesetzt ;)

**Comment by AMatutat** [comment]
@jedi101 kannst du bei Zeiten mal hier durchgucken und prüfen ob das jetzt alles erledigt ist? Ist irgendwie nach unten durchgerutscht. 
Carsten hat ja schon ne ganz gute Liste geschrieben

**Comment by jedi101** [comment]
@AMatutat - Ich arbeite die Liste noch einmal durch und schaue was evtl. noch gemacht werden muss. In diesem Zuge passe ich auch den englischen Quickstart_en.md an, das stört mich die ganze Zeit schon das die hinterher hinkt.
