### ISSUE TITLE
[BUG] Englischer Quickstart outdated

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/dungeon-starter#89]
Der Englische Quickstart ist outdated und muss (nahe zu vollständig) überarbeitet werden.

**Comment by cagix** [comment]
Wenn ich das so sehe: Wird uns das immer wieder passieren? Sollten wir dann überhaupt eine engl. Variante pflegen? Die Leute können ja eigentlich auch DeepL oder so nutzen?
