### ISSUE TITLE
Porbleme mit Quickstart Windows 11 IntelliJ 

### ISSUE THREAD

**Issue by refiver** [PM-Dungeon/dungeon-starter#92]
Quickstart nicht möglich. Gradle-Build schlägt fehl.
Mögliche Lösungen:
Pfade für Java im OS neu setzen, z.B. JAVA_HOME
JDK-Version in IntelliJ anpassen (17 sollte im Vergleich zu 18 keine Probleme machen)
Entweder das gradle-Skript im Terminal von IntelliJ ausführen oder z.B. in der Git-Bash
IntelliJ-Version heruntersetzen (in der JetBrains-Tollbox)

**Comment by jedi101** [comment]
@refiver - Hier in dem [Wiki](https://github.com/PM-Dungeon/dungeon-starter/wiki/FAQ#problem-gradlebuild-schl%C3%A4gt-fehl) des `dungeon-starter` haben wir eine kleine Rubrik mit [FAQs](https://github.com/PM-Dungeon/dungeon-starter/wiki/FAQ) die dieses Thema evtl. schon behandeln. Findest Du die dort beschriebene "Lösung" dieses Problems aussagekräftig genug oder sollten wir diese Deiner Meinung nach noch um eine konkretere Hilfestellung ergänzen?

**Comment by refiver** [comment]
Ich denke, der Teil mit dem setzen der richtigen Pfade im OS ist noch ein Punkt der aufgenommen werden kann, falls es nicht nur in IntelliJ fehlschlägt, sondern auch in der System-Konsole. Gesendet von Mail für Windows Von: JdGesendet: Donnerstag, 21. April 2022 18:40An: PM-Dungeon/dungeon-starterCc: refiver; MentionBetreff: Re: [PM-Dungeon/dungeon-starter] Porbleme mit Quickstart Windows 11 IntelliJ (Issue ***@***.*** - Hier in dem Wiki des dungeon-starter haben wir eine kleine Rubrik mit FAQs die dieses Thema evtl. schon behandeln. Findest Du die dort beschriebene "Lösung" dieses Problems aussagekräftig genug oder sollten wir diese Deiner Meinung nach noch um eine konkretere Hilfestellung ergänzen?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by jedi101** [comment]
@refiver - Ich habe den entsprechenden Eintrag im [Wiki](https://github.com/PM-Dungeon/dungeon-starter/wiki/FAQ#problem-gradlebuild-schl%C3%A4gt-fehl) um den von Dir angesprochenen Punkt ergänzt. Wäre super wenn Du da noch einmal einen Blick darauf werfen könntest ob dies jetzt ein wenig verständlicher ist.

**Comment by cagix** [comment]
> JDK-Version in IntelliJ anpassen (17 sollte im Vergleich zu 18 keine Probleme machen)

Aber stand nicht überall, dass wir Java 17 LTS einsetzen und sonst nix?

**Comment by cagix** [comment]
@jedi101 hängt das mit #96 zusammen?

**Comment by jedi101** [comment]
@cagix Nein, ich habe hier nur die FAQs vom Wiki dementsprechend angepasst. Da gab es leider keinen Pullrequest für.

**Comment by refiver** [comment]
Ich denke schon nur war mein System auf einem anderen Stand bevor ich angefangen habe und dies hat dementsprechend dann zu Problemen geführt.  Gesendet von Mail für Windows Von: Carsten GipsGesendet: Donnerstag, 21. April 2022 21:16An: PM-Dungeon/dungeon-starterCc: refiver; MentionBetreff: Re: [PM-Dungeon/dungeon-starter] Porbleme mit Quickstart Windows 11 IntelliJ (Issue #92) JDK-Version in IntelliJ anpassen (17 sollte im Vergleich zu 18 keine Probleme machen)Aber stand nicht überall, dass wir Java 17 LTS einsetzen und sonst nix?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by cagix** [comment]
verstehe.

**Comment by jedi101** [comment]
Ich mache hier mal zu. Die zusätzlichen Informationen zu `JAVA_HOME` wurden von mir in das Wiki eingepflegt.
