### ISSUE TITLE
[FEATURE] Mehr Level

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/dungeon-starter#93]
Durch die geringe Anzahl der bereitgestellten Level kommt es vor, dass das selbe Level zweimal hintereinander geladen wird. Das scheint für die Studis verwirrend zu sein.
Mehr Level senken diese Chance drastisch.

**Comment by jedi101** [comment]
@AMatutat Ich hatte mal ein Paar neue Raumtemplates für das generieren der Level mit Deinem Editor erzeugt. Wäre das beim erstellen unterschiedlicher Level hilfreich? Ein Problem auf das ich dabei gestoßen bin, und das ist auch der Grund weshalb ich die neuen Raumtemplates noch nicht gepushed habe ist, das ich dabei die Außenwände eines Raumes komplett als Tür angedacht hatte, da diese vom Algorithmus dann jeweils durch Wände ersetzt werden und nur eine Tür in verwendet wird, die vom Algorithmus auch vorgesehen ist. Aber irgendwie dauert das generieren der Level auf meinem System dann unverhältnismäßig lange und deshalb habe ich diese Raumtemplates noch nicht veröffentlicht. Da müsste ich die gegebenenfalls noch einmal überarbeiten.

**Comment by AMatutat** [comment]
Mehr Templates würden helfen.
Wenn alle Außenwände Türen sind, dann dauert es ewig. Bei der Suche nach einer Lösung wird dann jede Tür als eine Option betrachtet und je mehr Optionen es gibt, desto mehr muss berechnet werden. Daher nur wenige Türen pro Template einbauen.

**Comment by jedi101** [comment]
@AMatutat Dann erstelle ich die Templates noch einmal mit wenig Türen in den Räumen und erstelle dann einen Pullrequest.

**Comment by AMatutat** [comment]
Vermutlich outdated https://github.com/PM-Dungeon/core/issues/319#issuecomment-1132822433
