### ISSUE TITLE
[FEATURE] JDK Kompatibilität 

### ISSUE THREAD

**Issue by AMatutat** [PM-Dungeon/dungeon-starter#94]
Wir sollten in der Readme/ dem Quickstart auf https://github.com/PM-Dungeon/core/wiki/JDK-Kompatibilit%C3%A4t verlinken.

**Comment by cagix** [comment]
@jedi101 ich assigne dich mal, damit das ticket nicht in der luft hängen bleibt. du bist ja sowieso mit dem fix in #96 unterwegs ...
