### ISSUE TITLE
[BUG] Dungeon lässt sich unter Linux mit OpenJDK 17 nicht ausführen

### ISSUE THREAD

**Issue by JudiTeller** [PM-Dungeon/dungeon-starter#95]
**Fehlerbeschreibung** 
Unter Linux Pop-OS! 21.10 in IntelliJ konnte der Dungeon nicht mit der OpenJDK Java-Version 17 gestartet werden.
Fehlermeldung:
`Inconsistency detected by ld.so: dl-lookup.c: 105: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!`

**Anleitung zum Reproduzieren** 
OpenJDK 17 als Projekt-SDK festlegen
Dungeon entweder per

- ./gradlew run
- vorkonfigurierte Ausführung per IDE Oberfläche

**Erwartetes Verhalten** 
Das Spiel sollte starten und der Dungeon zu sehen sein

**Screenshots** 
![image](https://user-images.githubusercontent.com/59529322/164505823-8f0542c7-7b9d-4d12-8212-dd2b2f217471.png)

**Systembeschreibung (Bitte füllen Sie die folgenden Informationen aus)**
- Betriebssystem:
  - Pop-OS! 21.10
  - IntelliJ 2021.2.4 - build 212.5712.43
- Java Version (JDK):
  - OpenJDK 17.0.2

**Zusätzlicher Kontext**
Änderung der SDK Version auf Adoptium Temurin 17 oder 18 löst das Problem

**Comment by cagix** [comment]
@jedi101 ich assigne dich mal, damit das ticket nicht in der luft hängen bleibt. du bist ja sowieso mit dem fix in #96 unterwegs ...

**Comment by AMatutat** [comment]
> Unter Linux Pop-OS! 21.10 in IntelliJ konnte der Dungeon nicht mit der OpenJDK Java-Version 17 gestartet werden.
Fehlermeldung:

@jedi101 wir haben im Wiki ne Tabelle mit Kompatiblen und nicht Kompatiblen Systemen + JDK Versionen. Das dann einmal unter non-kompatibel einfügen.

**Comment by jedi101** [comment]
@AMatutat - Habe `Pop-OS! 21.10` mit `OpenJDK 17.0.2` zur "funktionier nicht" -Liste hinzugefügt und die Konfiguration `Pop-OS! 21.10` mit `Adoptium Temurin 17` zur "funktioniert-Liste". Siehe: [Kompatibilitätsliste](https://github.com/PM-Dungeon/core/wiki/JDK-Kompatibilit%C3%A4t)

**Comment by cagix** [comment]
kann dann hier zu?

**Comment by jedi101** [comment]
Ich denke schon.
